{
  "openapi": "3.0.0",
  "info": {
    "title": "Contact Book",
    "version": "1.0.0",
    "description": "[http://localhost:8000/swagger.json](http://localhost:8000/swagger.json)"
  },
  "paths": {
    "/api/user/register": {
      "post": {
        "summary": "Register a new user",
        "tags": [
          "User Table"
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "username": {
                    "type": "string",
                    "example": "exampleusername"
                  },
                  "email": {
                    "type": "string",
                    "example": "example@gmail.com"
                  },
                  "password": {
                    "type": "string",
                    "example": "bcrypt"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "User registered successfully",
            "content": {
              "application/json": {
                "example": {
                  "status": "SUCCESS",
                  "msg": "user register successfully",
                  "data": {
                    "username": "exampleusername",
                    "email": "abc@gmail.com",
                    "password": "bcrypt",
                    "createdAt": "2023-09-14T11:53:14.579Z",
                    "updatedAt": "2023-09-14T11:53:14.579Z"
                  }
                }
              }
            }
          },
          "403": {
            "description": "User already registered",
            "content": {
              "application/json": {
                "example": {
                  "status": "FAILED",
                  "msg": "User already registered",
                  "data": null
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/json": {
                "example": {
                  "status": "FAILED",
                  "msg": "Internal Server Error",
                  "data": null
                }
              }
            }
          }
        }
      }
    },
    "/api/user/login": {
      "post": {
        "summary": "Login a new user",
        "tags": [
          "User Table"
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "type": "object",
                "properties": {
                  "email": {
                    "type": "string",
                    "example": "example@gmail.com"
                  },
                  "password": {
                    "type": "string",
                    "example": "bcrypt"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "User Login successfully",
            "content": {
              "application/json": {
                "example": {
                  "status": "SUCCESS",
                  "msg": "User Login successfully",
                  "data": {
                    "token": "exampletoken",
                    "username": "exampleusername",
                    "email": "abc@gmail.com",
                    "password": "bcrypt",
                    "createdAt": "2023-09-14T11:53:14.579Z",
                    "updatedAt": "2023-09-14T11:53:14.579Z"
                  }
                }
              }
            }
          },
          "401": {
            "description": "Error Unauthorized Wrong password",
            "content": {
              "application/json": {
                "example": {
                  "status": "FAILED",
                  "msg": "Error Unauthorized Wrong password",
                  "data": null
                }
              }
            }
          },
          "403": {
            "description": "User Not a register",
            "content": {
              "application/json": {
                "example": {
                  "status": "FAILED",
                  "msg": "User Not a register",
                  "data": null
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/json": {
                "example": {
                  "status": "FAILED",
                  "msg": "Internal Server Error",
                  "data": null
                }
              }
            }
          }
        }
      }
    },
    "/api/user/me": {
      "get": {
        "summary": "Get user data.",
        "tags": [
          "User Table"
        ],
        "description": "Retrieves the user's data.",
        "security": [
          {
            "BearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "x-auth-token",
            "in": "header",
            "required": true,
            "description": "Enter a user Token",
            "schema": {
              "type": "string",
              "format": "Bearer [token]"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Successful response with user data.",
            "content": {
              "application/json": {
                "example": {
                  "status": "SUCCESS",
                  "msg": "Successful response with user data.",
                  "data": {
                    "username": "exampleusername",
                    "email": "abc@gmail.com",
                    "password": "bcrypt",
                    "createdAt": "2023-09-14T11:53:14.579Z",
                    "updatedAt": "2023-09-14T11:53:14.579Z"
                  }
                }
              }
            }
          },
          "403": {
            "description": "invalid token",
            "content": {
              "application/json": {
                "example": {
                  "status": "FAILED",
                  "msg": "invalid token",
                  "data": null
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/json": {
                "example": {
                  "status": "FAILED",
                  "msg": "Internal Server Error",
                  "data": null
                }
              }
            }
          }
        }
      }
    },
    "/api/book/addbookdetail": {
      "post": {
        "summary": "Add Book detail",
        "tags": [
          "Book Table"
        ],
        "security": [
          {
            "BearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "x-auth-token",
            "in": "header",
            "required": true,
            "description": "Enter a user Token",
            "schema": {
              "type": "string",
              "format": "Bearer [token]"
            }
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "properties": {
                  "bookname": {
                    "type": "string"
                  },
                  "authorname": {
                    "type": "string"
                  },
                  "bookimg": {
                    "type": "string"
                  },
                  "bookversion": {
                    "type": "string"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Book added successfully!!!",
            "content": {
              "application/json": {
                "example": {
                  "status": "SUCCESS",
                  "msg": "Book added successfully!!!",
                  "data": {
                    "bookname": "thinking",
                    "authorname": "vivekanand",
                    "bookimg": "url@12s21fasfasdf",
                    "bookversion": "v.0.0.01",
                    "createdAt": "2023-09-14T11:53:14.579Z",
                    "updatedAt": "2023-09-14T11:53:14.579Z"
                  }
                }
              }
            }
          },
          "403": {
            "description": "Book already added",
            "content": {
              "application/json": {
                "example": {
                  "status": "FAILED",
                  "msg": "Book already added",
                  "data": null
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/json": {
                "example": {
                  "status": "FAILED",
                  "msg": "Internal Server Error",
                  "data": null
                }
              }
            }
          }
        }
      }
    },
    "/api/book/update/{bookId}": {
      "put": {
        "summary": "Update Book detail",
        "tags": [
          "Book Table"
        ],
        "security": [
          {
            "BearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "x-auth-token",
            "in": "header",
            "required": true,
            "description": "Enter a user Token in the format 'Bearer [token]'",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "bookId",
            "in": "path",
            "required": true,
            "description": "ID of the book to update.",
            "schema": {
              "type": "string"
            }
          }
        ],
        "requestBody": {
          "required": true,
          "content": {
            "application/json": {
              "schema": {
                "properties": {
                  "bookname": {
                    "type": "string"
                  },
                  "authorname": {
                    "type": "string"
                  },
                  "bookimg": {
                    "type": "string"
                  },
                  "bookversion": {
                    "type": "string"
                  }
                }
              }
            }
          }
        },
        "responses": {
          "200": {
            "description": "Book updated successfully!!!",
            "content": {
              "application/json": {
                "example": {
                  "status": "SUCCESS",
                  "msg": "Book updated successfully!!!",
                  "data": {
                    "bookname": "updatethinking",
                    "authorname": "updatevivekanand",
                    "bookimg": "updateurl@12s21fasfasdf",
                    "bookversion": "updatev.0.0.01",
                    "createdAt": "2023-09-14T11:53:14.579Z",
                    "updatedAt": "2023-09-14T11:53:14.579Z"
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized - Invalid token or no token provided.",
            "content": {
              "application/json": {
                "example": {
                  "status": "FAILED",
                  "msg": "Unauthorized - Invalid token or no token provided.",
                  "data": null
                }
              }
            }
          },
          "403": {
            "description": "Forbidden - Invalid user request or book not found.",
            "content": {
              "application/json": {
                "example": {
                  "status": "FAILED",
                  "msg": "Forbidden - Invalid user request or book not found.",
                  "data": null
                }
              }
            }
          },
          "404": {
            "description": "Book not found.",
            "content": {
              "application/json": {
                "example": {
                  "status": "FAILED",
                  "msg": "Book not found.",
                  "data": null
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/json": {
                "example": {
                  "status": "FAILED",
                  "msg": "Internal Server Error",
                  "data": null
                }
              }
            }
          }
        }
      }
    },
    "/api/book/delete/{bookId}": {
      "delete": {
        "summary": "Delete a Book.",
        "tags": [
          "Book Table"
        ],
        "security": [
          {
            "BearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "bookId",
            "in": "path",
            "required": true,
            "description": "ID of the book to delete.",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "x-auth-token",
            "in": "header",
            "required": true,
            "description": "Enter a user Token in the format 'Bearer [token]'",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Book deleted successfully!!!",
            "content": {
              "application/json": {
                "example": {
                  "status": "SUCCESS",
                  "msg": "Book deleted successfully!!!",
                  "data": {
                    "bookname": "deletedthinking",
                    "authorname": "deletedvivekanand",
                    "bookimg": "deletedurl@12s21fasfasdf",
                    "bookversion": "deletedv.0.0.01",
                    "createdAt": "2023-09-14T11:53:14.579Z",
                    "updatedAt": "2023-09-14T11:53:14.579Z"
                  }
                }
              }
            }
          },
          "401": {
            "description": "Unauthorized - Invalid token or no token provided.",
            "content": {
              "application/json": {
                "example": {
                  "status": "FAILED",
                  "msg": "Unauthorized - Invalid token or no token provided.",
                  "data": null
                }
              }
            }
          },
          "404": {
            "description": "Book not found.",
            "content": {
              "application/json": {
                "example": {
                  "status": "FAILED",
                  "msg": "Book not found.",
                  "data": null
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/json": {
                "example": {
                  "status": "FAILED",
                  "msg": "Internal Server Error",
                  "data": null
                }
              }
            }
          }
        }
      }
    },
    "/api/book/getallbook": {
      "get": {
        "summary": "Get all Books.",
        "tags": [
          "Book Table"
        ],
        "security": [
          {
            "BearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "x-auth-token",
            "in": "header",
            "required": true,
            "description": "Enter a user Token in the format 'Bearer [token]'",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "content": {
              "application/json": {
                "example": {
                  "status": "SUCCESS",
                  "msg": "get all book successfully!!!",
                  "data": {
                    "bookname": "onethinking",
                    "authorname": "onevivekanand",
                    "bookimg": "oneurl@12s21fasfasdf",
                    "bookversion": "onev.0.0.01",
                    "createdAt": "2023-09-14T11:53:14.579Z",
                    "updatedAt": "2023-09-14T11:53:14.579Z"
                  }
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/json": {
                "example": {
                  "status": "FAILED",
                  "msg": "Internal Server Error",
                  "data": null
                }
              }
            }
          }
        }
      }
    },
    "/api/book/Searchbybook/{bookname}": {
      "get": {
        "summary": "Search for a book by name.",
        "tags": [
          "Book Table"
        ],
        "security": [
          {
            "BearerAuth": []
          }
        ],
        "parameters": [
          {
            "name": "x-auth-token",
            "in": "header",
            "required": true,
            "description": "Enter a user Token in the format 'Bearer [token]'",
            "schema": {
              "type": "string"
            }
          },
          {
            "name": "bookname",
            "in": "path",
            "required": true,
            "description": "Name of the book to search for.",
            "schema": {
              "type": "string"
            }
          }
        ],
        "responses": {
          "200": {
            "description": "Book found.",
            "content": {
              "application/json": {
                "status": "SUCCESS",
                "msg": "get  book successfully!!!",
                "data": {
                  "bookname": "searchthinking",
                  "authorname": "searchvivekanand",
                  "bookimg": "search@12s21fasfasdf",
                  "bookversion": "searchv.0.0.01",
                  "createdAt": "2023-09-14T11:53:14.579Z",
                  "updatedAt": "2023-09-14T11:53:14.579Z"
                }
              }
            }
          },
          "404": {
            "description": "Book not found.",
            "content": {
              "application/json": {
                "example": {
                  "status": "FAILED",
                  "msg": "Book not found.",
                  "data": null
                }
              }
            }
          },
          "500": {
            "description": "Internal Server Error",
            "content": {
              "application/json": {
                "example": {
                  "status": "FAILED",
                  "msg": "Internal Server Error",
                  "data": null
                }
              }
            }
          }
        }
      }
    }
  },
  "components": {},
  "tags": []
}